### ISSUE TITLE
[FEATURE]建议函数库支持超长脚本执行

### ISSUE THREAD

**Issue by linfengjjj** [1Panel-dev/MaxKB#1680]
### MaxKB 版本

v1.7.1

### 请描述您的需求或者改进建议

目前最新版本，函数库中脚本内容接近2000行时，执行会报错“argument list too long‘
![image](https://github.com/user-attachments/assets/24fa46ad-3fdc-4bea-81aa-3de3c10fc16d)

### 请描述你建议的实现方案

建议脚本内容过长时，分批处理或支持快捷方式调整相关参数，支持长脚本执行。

### 附加信息

![image](https://github.com/user-attachments/assets/05329d02-3557-468b-ab00-f00c6e1c53ff)
参考链接：https://blog.51cto.com/u_16213364/12040329

2024-11-20 15:53:18 [ERROR] [Errno 7] Argument list too long: '/opt/py3/bin/python':Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/auth/authentication.py", line 93, in run
    return func(view, request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/function_lib/views/function_lib_views.py", line 57, in post
    FunctionLibSerializer.Debug(data={'user_id': request.user.id}).debug(
  File "/opt/maxkb/app/apps/function_lib/serializers/function_lib_serializer.py", line 157, in debug
    return function_executor.exec_code(code, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/util/function_code.py", line 74, in exec_code
    subprocess_result = self._exec(_exec_code)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/util/function_code.py", line 99, in _exec
    return subprocess.run([python_directory, '-c', _code], text=True, capture_output=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/opt/py3/bin/python'

**Comment by baixin513** [comment]
感谢反馈，“argument list too long“ 是你自定义函数中的参数长度太长，可以检查一下你的函数。

**Comment by linfengjjj** [comment]
好像是我们把函数库脚本当作参数传入执行函数，函数库脚本太长就会报错这个，客户减少了一些脚本行数就正常的。
<img width="695" alt="5b829d4753945000ae4d98671930ff3" src="https://github.com/user-attachments/assets/0b23b69d-0051-495b-9b1b-28f5277e71b1">

**Comment by shaohuzhang1** [comment]
你是本地执行的把,官方镜像会执行_exec_sandbox

**Comment by shaohuzhang1** [comment]
你是本地启动的maxkb执行函数库吗,使用官方镜像不会出现这个问题

**Comment by linfengjjj** [comment]
我写了几千行print，调试函数库会出现argument list too long，脚本本身是没有函数和超长参数的，应该是应用代码中抛出的。
![image](https://github.com/user-attachments/assets/517eecd6-20fb-486a-89b7-1c07ab60f41f)
![image](https://github.com/user-attachments/assets/b2875a2c-b8a7-4fea-92c8-c777f66a6ade)

**Comment by linfengjjj** [comment]
减少到1000多行print，调试就正常了。
![image](https://github.com/user-attachments/assets/6e7ff4ed-2a28-4934-9daf-033eecfc3dc1)
![image](https://github.com/user-attachments/assets/ba9cdd6d-a3d5-4648-a258-d24ed3a03b3e)
