### ISSUE TITLE
[BUG] 启动应用的时候报错，提示'dataset_setting'

### ISSUE THREAD

**Issue by songofhawk** [1Panel-dev/MaxKB#218]
### 联系方式

songofhawk@gmail.com

### MaxKB 版本

-

## 环境
开发环境
* OS: MAC
* Python: 3.11.x
* Postgresql：15.x
* Node: 20.x

## 问题
* 新建模型成功：本地 ollama + llama3（本地模型，命令行实测可用 `ollama run llama3`）
* 新建应用成功：在设置页面"调试预览"框中，可以正常对话
* 但是点击演示按钮，新打开的页面会提示：“抱歉，当前正在维护，无法提供服务，请稍后再试！”，并且弹出 'dataset_setting' Alert

### 重现步骤

* 后端启动：`python3 main.py start`
* 前端启动：`npm run dev`
* 新建模型成功：本地 ollama + llama3（本地模型，命令行实测可用 `ollama run llama3`）
* 新建应用成功：在设置页面"调试预览"框中，可以正常对话
* 但是点击演示按钮，新打开的页面会提示：“抱歉，当前正在维护，无法提供服务，请稍后再试！”，并且弹出 'dataset_setting' Alert

### 期待的正确结果

演示页面可以正常工作

### 相关日志输出

```shell
Python 端控制台输出：

2024-04-23 11:57:04 [handle_exception ERROR] 'dataset_setting':Traceback (most recent call last):
  File "/Users/helix/gitrepo/MaxKB/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/helix/gitrepo/MaxKB/apps/application/views/application_views.py", line 175, in get
    'user_id': request.user.id}).profile())
                                 ^^^^^^^^^
  File "/Users/helix/gitrepo/MaxKB/apps/application/serializers/application_serializers.py", line 440, in profile
    return ApplicationSerializer.Query.reset_application(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/helix/gitrepo/MaxKB/apps/application/serializers/application_serializers.py", line 383, in reset_application
    application['dataset_setting'] = {**application['dataset_setting'], 'search_mode': 'embedding'}
                                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'dataset_setting'

```
```


### 附加信息

_No response_

**Comment by baixin513** [comment]
感谢反馈，请切换到v 1.0.4 tag  , main分支 是当前开发分支，开发过程中会存在一些问题。

**Comment by songofhawk** [comment]
不对啊，我已经切换到 [v1.0.4](https://github.com/1Panel-dev/MaxKB/releases/tag/v1.0.4) 这个分支了，还是报同样的错啊
