### ISSUE TITLE
[FEATURE]支持环境变量配置PostgreSQL / pgvector数据库

### ISSUE THREAD

**Issue by hurricanetx** [1Panel-dev/MaxKB#31]
### MaxKB 版本

0.9.1

### 请描述您的需求或者改进建议

因服务器资源有限，希望PostgreSQL / pgvector能够被重用，能很好的负载均衡，因此期望MaxKB在部署时能够通过环境变量设置指定数据库服务器，来启动服务。

### 请描述你建议的实现方案

通过环境变量设置指定数据库服务器，来启动服务。

**Comment by liqiang-fit2cloud** [comment]
目前支持通过配置文件指定数据库。
```
docker run -d --name=maxkb -p 8080:8080 -v ~/.maxkb:/var/lib/postgresql/data -v {你自己的配置文件}:/opt/maxkb/conf/config.yaml 1panel/maxkb python /opt/maxkb/app/main.py start
```

**Comment by liqiang-fit2cloud** [comment]
> docker run -d --name=maxkb -p 8080:8080 -v {你自己的配置文件}:/opt/maxkb/conf/config.yaml 1panel/maxkb python /opt/maxkb/app/main.py start

上述命令里的python /opt/maxkb/app/main.py start只会启动maxkb应用，不会启动maxkb内置的数据库，你可以通过你自己的配置文件指定其他数据库。
另外1Panel里的PostgreSQL需要安装pgvector插件才能运行maxkb。

**Comment by geosmart** [comment]
```yaml
version: '3.5'
services:
  db:
    image: cr2.fit2cloud.com/1panel/maxkb
    container_name: maxkb
    restart: always
    ports:
      - 9080:8080
    volumes:
      - ./config.yaml:/opt/maxkb/conf/config.yaml
    entrypoint: "python /opt/maxkb/app/main.py start"
```
挂载了配置文件，启动还是报错,postgresql的配置不生效，还是连接的127.0.0.1:5432
```bash
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
DEBUG:jieba:Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.529 seconds.
DEBUG:jieba:Loading model cost 0.529 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/py3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:
```

配置
```yaml
# 邮箱配置
EMAIL_ADDRESS: ${EMAIL_ADDRESS}
EMAIL_USE_TLS: ${EMAIL_USE_TLS}
EMAIL_USE_SSL: ${EMAIL_USE_SSL}
EMAIL_HOST: ${EMAIL_HOST}
EMAIL_PORT: ${EMAIL_PORT}
EMAIL_HOST_USER: ${EMAIL_HOST_USER}
EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

# 数据库链接信息
DB_NAME: maxkb
DB_HOST: why.duckdns.org
DB_PORT: 15432
DB_USER: postgres
DB_PASSWORD: xsdsds
DB_ENGINE: django.db.backends.postgresql_psycopg2
EMBEDDING_MODEL_PATH: /opt/maxkb/model/embedding
EMBEDDING_MODEL_NAME: /opt/maxkb/model/embedding/shibing624_text2vec-base-chinese
DEBUG: true
```

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Currently, it supports specifying databases through configuration files.
>
> ```
> docker run -d --name=maxkb -p 8080:8080 -v {your own configuration file}:/opt/maxkb/conf/config.yaml 1panel/maxkb python /opt/maxkb/app/main.py start
> ```

Isn't the built-in pgvector still started using the default MaxKB image? Recently I saw a 1panel/maxkb:main version, which seemed to be without pgv, and then he withdrew it, I haven't had time to see it yet

**Comment by liqiang-fit2cloud** [comment]
> > 目前支持通过配置文件指定数据库。
> > ```
> > docker run -d --name=maxkb -p 8080:8080 -v {你自己的配置文件}:/opt/maxkb/conf/config.yaml 1panel/maxkb python /opt/maxkb/app/main.py start
> > ```
> 
> 请问使用默认MaxKB镜像，内置的pgvector不是还会照样启动吗？最近看到出了一个1panel/maxkb:main版本，好像是不带pgv的，然后他又撤回了，我还没来得及看到

用默认的MaxKB镜像可以指定CMD只启动MaxKB服务器，不启动PG。

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > Currently, it supports specifying databases through configuration files.
> > ```
> > docker run -d --name=maxkb -p 8080:8080 -v {your own configuration file}:/opt/maxkb/conf/config.yaml 1panel/maxkb python /opt/maxkb/app/main.py start
> > ```
>
> Isn't the built-in pgvector still started using the default MaxKB image? Recently I saw a 1panel/maxkb:main version, which seemed to be without pgv, and then he withdrew it, I haven't had time to see it yet

Using the default MaxKB image, you can specify that CMD only starts the MaxKB server and does not start PG.
