### ISSUE TITLE
[BUG]ollama配置完成后，进行提问总是报连接异常，换成阿里的则没有问题

### ISSUE THREAD

**Issue by ming942129344** [1Panel-dev/MaxKB#425]
### 联系方式

手机号15550333432

### MaxKB 版本

1.1.2

### 问题描述

自己本机的ollama配置完成后，在问答时请求不到，报错：异常Connection error.
换成阿里的则可以进行问答

### 重现步骤

![image](https://github.com/1Panel-dev/MaxKB/assets/28640107/07df0a84-3cb7-4ace-a234-0c28af1c11f9)
![image](https://github.com/1Panel-dev/MaxKB/assets/28640107/90f90c88-81b9-43e4-b190-3632921347cb)
![1715407499019](https://github.com/1Panel-dev/MaxKB/assets/28640107/73ab3cbe-7da9-4e7c-bbf4-a0a874f3c868)
![image](https://github.com/1Panel-dev/MaxKB/assets/28640107/4753a3b5-5ddf-47bc-818a-ab6815e2a947)

配置自己的ollmam连接异常；
![image](https://github.com/1Panel-dev/MaxKB/assets/28640107/0e080873-156f-4d9a-a999-08f541737464)
换成阿里的则可以。

### 相关日志输出

```shell
2024-05-11 14:09:17 [basehttp INFO] "GET /api/application/5c39bf78-0f4b-11ef-9c3b-0242ac110002/chat/9f04628e-0f5c-11ef-bc16-0242ac110002/chat_record/fe91b7d8-0f5c-11ef-95ad-0242ac110002 HTTP/1.1" 200 866
2024-05-11 14:09:25 2024-05-11 14:09:25 [basehttp INFO] "POST /api/application/chat/open HTTP/1.1" 200 88
2024-05-11 14:09:28 2024-05-11 14:09:28 [base_chat_step ERROR] Connection error.:Traceback (most recent call last):
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
2024-05-11 14:09:28     yield
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
2024-05-11 14:09:28     resp = self._pool.handle_request(req)
2024-05-11 14:09:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
2024-05-11 14:09:28     raise exc from None
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
2024-05-11 14:09:28     response = connection.handle_request(
2024-05-11 14:09:28                ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
2024-05-11 14:09:28     return self._connection.handle_request(request)
2024-05-11 14:09:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
2024-05-11 14:09:28     raise exc
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 93, in handle_request
2024-05-11 14:09:28     self._send_request_headers(**kwargs)
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 151, in _send_request_headers
2024-05-11 14:09:28     with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
2024-05-11 14:09:28   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
2024-05-11 14:09:28     self.gen.throw(typ, value, traceback)
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-05-11 14:09:28     raise to_exc(exc) from exc
2024-05-11 14:09:28 httpcore.LocalProtocolError: Illegal header value b'Bearer  '
2024-05-11 14:09:28 
2024-05-11 14:09:28 The above exception was the direct cause of the following exception:
2024-05-11 14:09:28 
2024-05-11 14:09:28 Traceback (most recent call last):
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_base_client.py", line 952, in _request
2024-05-11 14:09:28     response = self._client.send(
2024-05-11 14:09:28                ^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
2024-05-11 14:09:28     response = self._send_handling_auth(
2024-05-11 14:09:28                ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
2024-05-11 14:09:28     response = self._send_handling_redirects(
2024-05-11 14:09:28                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
2024-05-11 14:09:28     response = self._send_single_request(request)
2024-05-11 14:09:28                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
2024-05-11 14:09:28     response = transport.handle_request(request)
2024-05-11 14:09:28                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
2024-05-11 14:09:28     with map_httpcore_exceptions():
2024-05-11 14:09:28   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
2024-05-11 14:09:28     self.gen.throw(typ, value, traceback)
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
2024-05-11 14:09:28     raise mapped_exc(message) from exc
2024-05-11 14:09:28 httpx.LocalProtocolError: Illegal header value b'Bearer  '
2024-05-11 14:09:28 
2024-05-11 14:09:28 The above exception was the direct cause of the following exception:
2024-05-11 14:09:28 
2024-05-11 14:09:28 Traceback (most recent call last):
2024-05-11 14:09:28   File "/opt/maxkb/app/apps/application/chat_pipeline/step/chat_step/impl/base_chat_step.py", line 55, in event_content
2024-05-11 14:09:28     for chunk in response:
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 249, in stream
2024-05-11 14:09:28     raise e
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 229, in stream
2024-05-11 14:09:28     for chunk in self._stream(messages, stop=stop, **kwargs):
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 398, in _stream
2024-05-11 14:09:28     for chunk in self.completion_with_retry(
2024-05-11 14:09:28                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 356, in completion_with_retry
2024-05-11 14:09:28     return self.client.create(**kwargs)
2024-05-11 14:09:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
2024-05-11 14:09:28     return func(*args, **kwargs)
2024-05-11 14:09:28            ^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 590, in create
2024-05-11 14:09:28     return self._post(
2024-05-11 14:09:28            ^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_base_client.py", line 1240, in post
2024-05-11 14:09:28     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
2024-05-11 14:09:28                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_base_client.py", line 921, in request
2024-05-11 14:09:28     return self._request(
2024-05-11 14:09:28            ^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_base_client.py", line 976, in _request
2024-05-11 14:09:28     return self._retry_request(
2024-05-11 14:09:28            ^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_base_client.py", line 1053, in _retry_request
2024-05-11 14:09:28     return self._request(
2024-05-11 14:09:28            ^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_base_client.py", line 976, in _request
2024-05-11 14:09:28     return self._retry_request(
2024-05-11 14:09:28            ^^^^^^^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_base_client.py", line 1053, in _retry_request
2024-05-11 14:09:28     return self._request(
2024-05-11 14:09:28            ^^^^^^^^^^^^^^
2024-05-11 14:09:28   File "/opt/py3/lib/python3.11/site-packages/openai/_base_client.py", line 986, in _request
2024-05-11 14:09:28     raise APIConnectionError(request=request) from err
2024-05-11 14:09:28 openai.APIConnectionError: Connection error.
2024-05-11 14:09:28 
2024-05-11 14:09:28 2024-05-11 14:09:28 [basehttp INFO] "POST /api/application/chat_message/04cbb1ee-0f5d-11ef-8215-0242ac110002 HTTP/1.1" 200 182
2024-05-11 14:09:29 2024-05-11 14:09:29 [basehttp INFO] "GET /api/application/5c39bf78-0f4b-11ef-9c3b-0242ac110002/chat/04cbb1ee-0f5d-11ef-8215-0242ac110002/chat_record/04f63c8e-0f5d-11ef-8215-0242ac110002 HTTP/1.1" 200 72
```

**Comment by ming942129344** [comment]
API Key不能设置成空格。。
