### ISSUE TITLE
[BUG] 稍微大点、复杂点的 DOCX 就无法上传，无法分段预览

### ISSUE THREAD

**Issue by Jaylenwa** [1Panel-dev/MaxKB#462]
### MaxKB 版本

v1.1.2

### 问题描述

![Snipaste_2024-05-15_15-47-00](https://github.com/1Panel-dev/MaxKB/assets/65205528/a9173bb8-e432-46c5-8e0a-f11a2421ec38)

![Snipaste_2024-05-15_15-47-15](https://github.com/1Panel-dev/MaxKB/assets/65205528/6fc0d807-c09a-41e6-ae97-f12474e8024b)

### 重现步骤

创建知识库后 上传pdf
上传的pdf大小为11MB,未达到限制的50MB
右侧无法预览，点击上传后台报错

### 相关日志输出

2024-05-15 15:47:12 [handle_exception ERROR] :Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/auth/authentication.py", line 94, in run
    return func(view, request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/dataset/views/document.py", line 109, in post
    return result.success(DocumentSerializers.Batch(data={'dataset_id': dataset_id}).batch_save(request.data))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/util/common.py", line 51, in run
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/dataset/serializers/document_serializers.py", line 701, in batch_save
    return native_search(query_set, select_string=get_file_content(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/db/search.py", line 105, in native_search
    exec_sql, exec_params = generate_sql_by_query(queryset, select_string, field_replace_dict, with_table_name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/db/search.py", line 68, in generate_sql_by_query
    sql, params = compiler_queryset(queryset, field_replace_dict, with_table_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/db/search.py", line 86, in compiler_queryset
    sql, params = app_sql_compiler.get_query_str(with_table_name=with_table_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maxkb/app/apps/common/db/compiler.py", line 47, in get_query_str
    self.compile(self.where) if self.where is not None else ("", [])
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 506, in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/sql/where.py", line 130, in as_sql
    raise EmptyResultSet
django.core.exceptions.EmptyResultSet

_No response_

**Comment by baixin513** [comment]
你这边是不是二开的 ？ 上传的文档方便发给 xin.bai@fit2cloud.com

**Comment by Jaylenwa** [comment]
> 你这边是不是二开的 ？ 是不是官方的 docker安装的 maxkb? 上传的文档方便发给 [xin.bai@fit2cloud.com](mailto:xin.bai@fit2cloud.com)

不是 是使用的官方docker安装的。
似乎是我机器配置不够的原因，我报错的服务器是2c2G的配置，我换了一个高配置的就可以了
