### ISSUE TITLE
本地源码运行报错（drf-yasg）

### ISSUE THREAD

**Issue by xiaohaiqing** [1Panel-dev/MaxKB#607]
### MaxKB 版本

main

### 问题描述

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "D:\soft\Python310\lib\site-packages\django\core\servers\basehttp.py", line 48, in get_internal_wsgi_application
    return import_string(app_path)
  File "D:\soft\Python310\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "D:\soft\Python310\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "D:\soft\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\smartdoc\wsgi.py", line 27, in <module>
    post_handler()
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\smartdoc\wsgi.py", line 20, in post_handler
    from common import event
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\common\event\__init__.py", line 11, in <module>
    from .listener_manage import *
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\common\event\listener_manage.py", line 19, in <module>
    from common.config.embedding_config import VectorStore, EmbeddingModel
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\common\config\embedding_config.py", line 35, in <module>
    class VectorStore:
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\common\config\embedding_config.py", line 36, in VectorStore
    from embedding.vector.pg_vector import PGVector
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\embedding\vector\pg_vector.py", line 19, in <module>
    from common.db.search import generate_sql_by_query_dict
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\common\db\search.py", line 16, in <module>
    from common.response.result import Page
  File "D:\workspace\pyWorkSpace\demo\MaxKB\apps\common\response\result.py", line 4, in <module>
    from drf_yasg import openapi
  File "D:\soft\Python310\lib\site-packages\drf_yasg\openapi.py", line 11, in <module>
    from .utils import filter_none, force_real_str
ImportError: cannot import name 'filter_none' from 'drf_yasg.utils' (D:\soft\Python310\lib\site-packages\drf_yasg\utils.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\soft\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\soft\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\soft\Python310\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "D:\soft\Python310\lib\site-packages\django\core\management\commands\runserver.py", line 139, in inner_run
    handler = self.get_handler(*args, **options)
  File "D:\soft\Python310\lib\site-packages\django\contrib\staticfiles\management\commands\runserver.py", line 31, in get_handler
    handler = super().get_handler(*args, **options)
  File "D:\soft\Python310\lib\site-packages\django\core\management\commands\runserver.py", line 78, in get_handler
    return get_internal_wsgi_application()
  File "D:\soft\Python310\lib\site-packages\django\core\servers\basehttp.py", line 50, in get_internal_wsgi_application
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: WSGI application 'smartdoc.wsgi.application' could not be loaded; Error importing module.

### 重现步骤

当期插件版本：
Django：5.0.6
drf-yasg：1.21.7
在drf-yasg1.21.7源码中的utils.py文件中存在filter_none函数，但是不知道为啥会报这个错误

**Comment by baixin513** [comment]
抱歉，没看懂，二开报错请自行排查一下问题。

**Comment by xiaohaiqing** [comment]
ok，感谢

**Comment by xiaohaiqing** [comment]
> 抱歉，没看懂，二开报错请自行排查一下问题。 参考一下 wiki 上的开发环境搭建 https://github.com/1Panel-dev/MaxKB/wiki/%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA

ok，感谢

**Comment by XiaoYang1127** [comment]
应该是版本问题

**Comment by shaohuzhang1** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It should be a version issue
