### ISSUE TITLE
[BUG]V1.4开源版本不支持windwos运行

### ISSUE THREAD

**Issue by wucanhong** [1Panel-dev/MaxKB#915]
### MaxKB 版本

v1.4

### 问题描述

在v1.4中，使用开源代码运行时，提示ModuleNotFoundError: No module named 'fcntl' 、ModuleNotFoundError: No module named 'pwd' 、 AttributeError: module 'socket' has no attribute 'AF_UNIX' ，是不是不支持跨环境运行

### 重现步骤

克隆项目，并安装开发文档配置，执行python main.py start 时报错

### 期待的正确结果

可以正常在windows中运行开源项目

### 相关日志输出

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\CodePlace\MaxKB\MaxKB-1.4\venv\Scripts\gunicorn.exe\__main__.py", line 4, in <module>
  File "D:\CodePlace\MaxKB\MaxKB-1.4\venv\Lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "D:\CodePlace\MaxKB\MaxKB-1.4\venv\Lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "D:\CodePlace\MaxKB\MaxKB-1.4\venv\Lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by liqiang-fit2cloud** [comment]
支持的，我们自己开发就是用windows。
由于每个人编程能力和开发环境的差异，开发者在二开过程中遇到的问题项目组没有精力一一协助分析，请自行解决，感谢理解。

**Comment by shaohuzhang1** [comment]
使用
python main.py dev
启动

**Comment by wucanhong** [comment]
> 使用 python main.py dev 启动

谢谢大佬
